"use client";

const REPORT_SECTIONS = [
  "Executive Summary","Business Score (0–100)","Financial Forecast","Revenue Projections","Market Analysis",
  "Competitor Intelligence","SWOT Analysis","Marketing Strategy","Customer Persona","Launch Plan",
  "30-Day Roadmap","90-Day Roadmap","Growth Strategy","Risk Analysis","Action Checklist",
];

const FEATURES = [
  { title: "Real Executive Thinking", description: "Not generic AI answers. Each executive produces their own perspective, data, and recommendations — just like a real board meeting.", icon: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="size-5"><path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96-.46 2.5 2.5 0 0 1-2.96-3.08 3 3 0 0 1-.34-5.58 2.5 2.5 0 0 1 1.32-4.24 2.5 2.5 0 0 1 4.44-1.14Z" /><path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96-.46 2.5 2.5 0 0 0 2.96-3.08 3 3 0 0 0 .34-5.58 2.5 2.5 0 0 0-1.32-4.24 2.5 2.5 0 0 0-4.44-1.14Z" /></svg> },
  { title: "Instant Financial Models", description: "Your CFO builds realistic revenue projections, expense forecasts, and break-even analysis specific to your business model.", icon: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="size-5"><line x1="18" y1="20" x2="18" y2="10" /><line x1="12" y1="20" x2="12" y2="4" /><line x1="6" y1="20" x2="6" y2="14" /></svg> },
  { title: "Competitive Intelligence", description: "Deep competitor analysis with positioning maps, gap analysis, and differentiation strategies built by your Business Analyst.", icon: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="size-5"><circle cx="11" cy="11" r="8" /><path d="m21 21-4.35-4.35" /></svg> },
  { title: "Exportable Reports", description: "Download beautiful PDF reports to share with investors, co-founders, or banks. Professional grade, presentation ready.", icon: <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="size-5"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" /></svg> },
];

export function FeaturesSection() {
  return (
    <section className="relative py-32 px-6">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-emerald-500/20 bg-emerald-500/5 mb-6">
            <span className="text-xs text-emerald-300 font-medium tracking-wide uppercase">Complete Strategy</span>
          </div>
          <h2 className="text-4xl sm:text-5xl font-bold text-white mb-4 tracking-tight">
            Everything You Need<br /><span className="gradient-text">Nothing You Don&apos;t</span>
          </h2>
          <p className="text-lg text-white/40 max-w-xl mx-auto">Every report contains 15+ professionally structured sections covering every aspect of your business.</p>
        </div>
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-start">
          <div className="relative">
            <div className="rounded-2xl glass-strong border border-white/[0.08] overflow-hidden">
              <div className="px-6 py-5 border-b border-white/[0.06] flex items-center gap-3">
                <div className="size-8 rounded-lg bg-gradient-to-br from-violet-600 to-blue-600 flex items-center justify-center">
                  <svg className="size-4 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" /><polyline points="14 2 14 8 20 8" /></svg>
                </div>
                <div>
                  <div className="text-sm font-semibold text-white">Business Strategy Report</div>
                  <div className="text-xs text-white/35">Generated by AI Executive Board</div>
                </div>
                <div className="ml-auto">
                  <span className="text-xs px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">Complete</span>
                </div>
              </div>
              <div className="px-6 py-5 border-b border-white/[0.06]">
                <div className="flex items-center justify-between mb-3">
                  <span className="text-sm text-white/50">Business Viability Score</span>
                  <span className="text-2xl font-bold gradient-text">87/100</span>
                </div>
                <div className="h-2 bg-white/[0.04] rounded-full overflow-hidden">
                  <div className="h-full w-[87%] bg-gradient-to-r from-violet-600 to-emerald-500 rounded-full" />
                </div>
                <div className="flex justify-between mt-1.5">
                  <span className="text-[10px] text-white/25">Poor</span>
                  <span className="text-[10px] text-emerald-400 font-medium">Excellent</span>
                </div>
              </div>
              <div className="p-6">
                <div className="text-xs font-medium text-white/30 uppercase tracking-widest mb-4">Report Contents</div>
                <div className="grid grid-cols-2 gap-2">
                  {REPORT_SECTIONS.map((section) => (
                    <div key={section} className="flex items-center gap-2">
                      <div className="size-4 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center flex-shrink-0">
                        <svg className="size-2.5 text-emerald-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><polyline points="20 6 9 17 4 12" /></svg>
                      </div>
                      <span className="text-xs text-white/50">{section}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
            <div className="absolute -top-4 -right-4 glass rounded-xl p-3 border border-white/[0.08] hidden lg:block">
              <div className="text-xs text-white/40 mb-1">Projected Revenue</div>
              <div className="text-lg font-bold text-emerald-400">$2.4M / yr</div>
            </div>
            <div className="absolute -bottom-4 -left-4 glass rounded-xl p-3 border border-white/[0.08] hidden lg:block">
              <div className="text-xs text-white/40 mb-1">Break-even</div>
              <div className="text-lg font-bold text-blue-400">Month 8</div>
            </div>
          </div>
          <div className="flex flex-col gap-6">
            {FEATURES.map((feature) => (
              <div key={feature.title} className="flex gap-4">
                <div className="size-10 rounded-xl bg-violet-500/10 border border-violet-500/20 flex items-center justify-center text-violet-400 flex-shrink-0 mt-0.5">{feature.icon}</div>
                <div>
                  <h3 className="text-base font-semibold text-white mb-1">{feature.title}</h3>
                  <p className="text-sm text-white/40 leading-relaxed">{feature.description}</p>
                </div>
              </div>
            ))}
            <div className="mt-4">
              <a href="/dashboard" className="inline-flex items-center gap-2 text-sm font-medium text-violet-400 hover:text-violet-300 transition-colors">
                View sample report
                <svg className="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12h14M12 5l7 7-7 7" /></svg>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
