import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { logSecurityEvent } from "@/lib/security-log";
import { createClient } from "@/lib/supabase/server";
import { verifyTotpCode, generateBackupCodes } from "@/lib/two-factor";
import { authLimiter, rateLimitResponse, clientIp } from "@/lib/middleware/rate-limit";
import { dbErrorResponse } from "@/lib/errors";

// POST /api/auth/2fa/verify  { code }
// Confirms the 6-digit code from the user's authenticator app matches the
// secret generated by /setup, then flips two_fa on and issues one-time
// backup codes (shown to the user exactly once, never returned again).
export async function POST(req: Request) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ success: false, error: "Unauthorized" }, { status: 401 });

  const limit = await authLimiter(`2fa-verify:${session.user.id}:${clientIp(req)}`);
  if (!limit.allowed) return rateLimitResponse(limit.resetAt);

  let body: { code?: string };
  try { body = await req.json(); } catch { return NextResponse.json({ success: false, error: "Некорректный запрос" }, { status: 400 }); }
  const code = (body.code ?? "").trim();
  if (!/^\d{6}$/.test(code)) {
    return NextResponse.json({ success: false, error: "Код должен состоять из 6 цифр" }, { status: 400 });
  }

  const supabase = await createClient();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = supabase as any;
  const { data: row } = await db.from("user_settings").select("two_fa_secret_enc").eq("user_id", session.user.id).maybeSingle();
  if (!row?.two_fa_secret_enc) {
    return NextResponse.json({ success: false, error: "Сначала запросите QR-код настройки" }, { status: 400 });
  }

  if (!(await verifyTotpCode(row.two_fa_secret_enc, code))) {
    return NextResponse.json({ success: false, error: "Неверный код. Проверьте время на устройстве и попробуйте ещё раз" }, { status: 400 });
  }

  const { plain, hashed } = await generateBackupCodes();
  const { error } = await db.from("user_settings").update({
    two_fa: true,
    two_fa_backup_codes: hashed,
    two_fa_verified_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }).eq("user_id", session.user.id);
  if (error) return dbErrorResponse(error, "/api/auth/2fa/verify");

  await logSecurityEvent(session.user.id, "2fa_enabled");
  return NextResponse.json({ success: true, backupCodes: plain });
}
