"use client";

import { useState } from "react";
import { Badge } from "@/components/ui/Badge";
import { Progress } from "@/components/ui/Progress";
import { Card, CardContent } from "@/components/ui/Card";

const TABS = [
  "Executive Summary",
  "Financial Model",
  "Market Analysis",
  "Marketing Strategy",
  "Operations",
  "Technology",
  "Risk Analysis",
  "Roadmap",
];

const EXECUTIVES_STATUS = [
  { role: "CEO", title: "Executive Director", status: "complete", color: "#7c3aed" },
  { role: "CFO", title: "Chief Financial Officer", status: "complete", color: "#3b82f6" },
  { role: "CMO", title: "Chief Marketing Officer", status: "complete", color: "#10b981" },
  { role: "Analyst", title: "Business Analyst", status: "complete", color: "#f59e0b" },
  { role: "COO", title: "Chief Operations Officer", status: "complete", color: "#ec4899" },
  { role: "Sales", title: "Sales Director", status: "complete", color: "#6366f1" },
  { role: "Legal", title: "Legal Advisor", status: "complete", color: "#6b7280" },
  { role: "CTO", title: "Chief Technology Officer", status: "complete", color: "#a855f7" },
];

export default function DemoProjectPage() {
  const [activeTab, setActiveTab] = useState("Executive Summary");

  return (
    <div className="p-6 max-w-7xl mx-auto">
      {/* Project header */}
      <div className="mb-6">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h1 className="text-xl font-bold text-white">AI-Powered Fitness Platform</h1>
              <Badge variant="success" dot>Strategy Complete</Badge>
            </div>
            <p className="text-sm text-white/35">SaaS · Mobile App · Just an idea · Generated by 8 AI Executives</p>
          </div>
          <div className="flex items-center gap-2">
            <button className="h-9 px-4 text-xs font-medium glass rounded-xl border border-white/[0.08] text-white/60 hover:text-white transition-all">
              <svg className="size-3.5 inline mr-1.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" /><polyline points="7 10 12 15 17 10" /><line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Export PDF
            </button>
            <button className="h-9 px-4 text-xs font-medium bg-gradient-to-r from-violet-600 to-blue-600 text-white rounded-xl hover:from-violet-500 hover:to-blue-500 transition-all">
              <svg className="size-3.5 inline mr-1.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" /><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
              </svg>
              Refine Strategy
            </button>
          </div>
        </div>

        {/* Business score */}
        <div className="mt-5 p-5 rounded-2xl glass border border-white/[0.07] flex items-center gap-8 flex-wrap">
          <div className="text-center">
            <div className="text-4xl font-bold gradient-text mb-1">87</div>
            <div className="text-xs text-white/35">Business Score</div>
          </div>
          <div className="flex-1 min-w-0 space-y-2.5">
            {[
              { label: "Market Opportunity", value: 91 },
              { label: "Financial Viability", value: 83 },
              { label: "Execution Feasibility", value: 87 },
              { label: "Competitive Advantage", value: 79 },
            ].map((item) => (
              <div key={item.label} className="flex items-center gap-3">
                <span className="text-xs text-white/40 w-40 flex-shrink-0">{item.label}</span>
                <Progress value={item.value} size="sm" className="flex-1" />
                <span className="text-xs text-white/50 w-8 text-right">{item.value}</span>
              </div>
            ))}
          </div>
          <div className="grid grid-cols-2 gap-x-8 gap-y-2">
            {[
              { label: "Projected Revenue", value: "$2.4M", color: "text-emerald-400" },
              { label: "Break-even", value: "Month 8", color: "text-blue-400" },
              { label: "Total Investment", value: "$185K", color: "text-amber-400" },
              { label: "ROI (Year 2)", value: "340%", color: "text-violet-400" },
            ].map((m) => (
              <div key={m.label}>
                <div className={`text-lg font-bold ${m.color}`}>{m.value}</div>
                <div className="text-[10px] text-white/30">{m.label}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Executive status */}
      <div className="mb-5 flex gap-2 flex-wrap">
        {EXECUTIVES_STATUS.map((exec) => (
          <div
            key={exec.role}
            className="flex items-center gap-2 px-3 py-1.5 rounded-full border"
            style={{ borderColor: `${exec.color}25`, background: `${exec.color}10` }}
          >
            <span className="size-1.5 rounded-full" style={{ background: "#10b981" }} />
            <span className="text-xs font-medium" style={{ color: exec.color }}>{exec.role}</span>
            <span className="text-[10px] text-white/30">Complete</span>
          </div>
        ))}
      </div>

      {/* Tabs */}
      <div className="flex gap-1 p-1 rounded-xl glass border border-white/[0.07] mb-6 overflow-x-auto">
        {TABS.map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`flex-shrink-0 px-4 py-2 rounded-lg text-xs font-medium transition-all duration-200 ${
              activeTab === tab
                ? "bg-violet-600 text-white shadow-lg shadow-violet-500/25"
                : "text-white/40 hover:text-white/70"
            }`}
          >
            {tab}
          </button>
        ))}
      </div>

      {/* Tab content */}
      {activeTab === "Executive Summary" && <ExecutiveSummaryTab />}
      {activeTab === "Financial Model" && <FinancialModelTab />}
      {activeTab === "Market Analysis" && <MarketAnalysisTab />}
      {activeTab === "Marketing Strategy" && <MarketingTab />}
      {activeTab === "Operations" && <OperationsTab />}
      {activeTab === "Technology" && <TechnologyTab />}
      {activeTab === "Risk Analysis" && <RiskTab />}
      {activeTab === "Roadmap" && <RoadmapTab />}
    </div>
  );
}

function Section({ title, executive, children }: { title: string; executive?: string; children: React.ReactNode }) {
  return (
    <Card className="mb-4">
      <CardContent className="p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-base font-semibold text-white">{title}</h3>
          {executive && (
            <span className="text-xs px-2.5 py-1 rounded-full bg-violet-500/10 border border-violet-500/20 text-violet-400">
              {executive}
            </span>
          )}
        </div>
        {children}
      </CardContent>
    </Card>
  );
}

function ExecutiveSummaryTab() {
  return (
    <div className="space-y-4">
      <Section title="CEO Executive Summary" executive="CEO">
        <div className="prose prose-sm prose-invert max-w-none space-y-3">
          <p className="text-sm text-white/60 leading-relaxed">
            After comprehensive analysis from all eight executive departments, the AI-Powered Fitness Platform presents a <strong className="text-white">high-potential opportunity</strong> in the rapidly growing digital health market, currently valued at $32 billion globally.
          </p>
          <p className="text-sm text-white/60 leading-relaxed">
            The business model leverages a subscription-first approach with AI-personalized workout and nutrition planning, targeting health-conscious millennials and Gen-Z consumers aged 22-40. Our competitive moat lies in proprietary AI algorithms that adapt to user behavior, a feature set lacking in current market leaders.
          </p>
          <p className="text-sm text-white/60 leading-relaxed">
            <strong className="text-white">Key Recommendation:</strong> Pursue a focused MVP launch strategy targeting urban professionals in the United States first, with international expansion planned for Year 2. Initial seed funding of $185,000 will sustain 18 months of runway with a lean team of 3-4 people.
          </p>
        </div>
      </Section>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[
          {
            title: "Biggest Opportunity",
            content: "80% of gym-goers quit within 3 months. AI personalization increases retention by 65%.",
            icon: "📈",
            color: "from-emerald-600/20 to-teal-600/20",
            border: "border-emerald-500/15",
          },
          {
            title: "Key Risk",
            content: "Market is crowded. Differentiation through AI quality and UX is critical to survival.",
            icon: "⚠️",
            color: "from-amber-600/20 to-orange-600/20",
            border: "border-amber-500/15",
          },
          {
            title: "First Move",
            content: "Launch MVP within 4 months. Target 500 paying users before raising Series A.",
            icon: "🚀",
            color: "from-violet-600/20 to-blue-600/20",
            border: "border-violet-500/15",
          },
        ].map((card) => (
          <div
            key={card.title}
            className={`p-4 rounded-xl bg-gradient-to-br ${card.color} border ${card.border}`}
          >
            <div className="text-2xl mb-2">{card.icon}</div>
            <div className="text-sm font-semibold text-white mb-1">{card.title}</div>
            <p className="text-xs text-white/50 leading-relaxed">{card.content}</p>
          </div>
        ))}
      </div>

      <Section title="SWOT Analysis" executive="Business Analyst">
        <div className="grid grid-cols-2 gap-3">
          {[
            { label: "Strengths", items: ["AI-powered personalization", "Low overhead model", "Subscription revenue", "Scalable technology"], color: "emerald" },
            { label: "Weaknesses", items: ["No brand recognition", "AI development cost", "Content creation needed", "Limited initial features"], color: "amber" },
            { label: "Opportunities", items: ["$32B growing market", "Post-COVID health focus", "Wearable integration", "B2B wellness market"], color: "blue" },
            { label: "Threats", items: ["Apple Fitness+, Nike Training", "Data privacy regulations", "User acquisition costs", "Economic downturn impact"], color: "red" },
          ].map((quadrant) => (
            <div key={quadrant.label} className={`p-4 rounded-xl bg-${quadrant.color}-500/5 border border-${quadrant.color}-500/15`}>
              <div className={`text-xs font-bold text-${quadrant.color}-400 uppercase tracking-widest mb-2`}>{quadrant.label}</div>
              <ul className="space-y-1">
                {quadrant.items.map((item) => (
                  <li key={item} className="text-xs text-white/50 flex items-start gap-1.5">
                    <span className={`text-${quadrant.color}-400 mt-0.5 flex-shrink-0`}>•</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}

function FinancialModelTab() {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: "Year 1 Revenue", value: "$287K", sub: "+∞ (launch year)", color: "text-emerald-400" },
          { label: "Year 2 Revenue", value: "$1.2M", sub: "+318% YoY", color: "text-emerald-400" },
          { label: "Year 3 Revenue", value: "$2.4M", sub: "+100% YoY", color: "text-emerald-400" },
          { label: "Break-even Month", value: "M8", sub: "8 months post-launch", color: "text-blue-400" },
        ].map((m) => (
          <Card key={m.label}>
            <CardContent className="p-4">
              <div className={`text-2xl font-bold ${m.color} mb-0.5`}>{m.value}</div>
              <div className="text-xs text-white/35">{m.label}</div>
              <div className="text-[10px] text-white/25 mt-0.5">{m.sub}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Section title="Revenue Model Breakdown" executive="CFO">
        <div className="space-y-4">
          {[
            { stream: "Individual Subscriptions ($19.99/mo)", year1: "$168K", year2: "$720K", year3: "$1.44M", pct: 60 },
            { stream: "Annual Plans ($149/yr)", year1: "$74K", year2: "$312K", year3: "$624K", pct: 26 },
            { stream: "Corporate Wellness B2B", year1: "$30K", year2: "$120K", year3: "$240K", pct: 10 },
            { stream: "Premium Features / Add-ons", year1: "$15K", year2: "$48K", year3: "$96K", pct: 4 },
          ].map((row) => (
            <div key={row.stream} className="space-y-1.5">
              <div className="flex items-center justify-between">
                <span className="text-sm text-white/70">{row.stream}</span>
                <div className="flex gap-6 text-xs text-white/40">
                  <span>Y1: <strong className="text-white/60">{row.year1}</strong></span>
                  <span>Y2: <strong className="text-white/60">{row.year2}</strong></span>
                  <span>Y3: <strong className="text-white/60">{row.year3}</strong></span>
                </div>
              </div>
              <Progress value={row.pct} size="sm" />
            </div>
          ))}
        </div>
      </Section>

      <Section title="Cost Structure" executive="CFO">
        <div className="grid grid-cols-2 gap-3">
          {[
            { category: "Development & Technology", monthly: "$8,500", annual: "$102K" },
            { category: "Marketing & Acquisition", monthly: "$5,000", annual: "$60K" },
            { category: "Team (2 FTE)", monthly: "$12,000", annual: "$144K" },
            { category: "Infrastructure & Tools", monthly: "$1,200", annual: "$14.4K" },
            { category: "Legal & Compliance", monthly: "$800", annual: "$9.6K" },
            { category: "G&A / Operations", monthly: "$1,500", annual: "$18K" },
          ].map((cost) => (
            <div key={cost.category} className="flex items-center justify-between p-3 rounded-xl bg-white/[0.03] border border-white/[0.05]">
              <span className="text-xs text-white/50">{cost.category}</span>
              <div className="text-right">
                <div className="text-sm font-semibold text-white">{cost.monthly}</div>
                <div className="text-[10px] text-white/25">/month</div>
              </div>
            </div>
          ))}
        </div>
        <div className="mt-4 p-4 rounded-xl bg-blue-500/5 border border-blue-500/15">
          <div className="flex justify-between items-center">
            <span className="text-sm text-white/60">Total Monthly Burn Rate</span>
            <span className="text-lg font-bold text-blue-400">$29,000</span>
          </div>
          <div className="flex justify-between items-center mt-1">
            <span className="text-xs text-white/30">Total Annual Operating Cost</span>
            <span className="text-sm font-semibold text-blue-300">$348,000</span>
          </div>
        </div>
      </Section>
    </div>
  );
}

function MarketAnalysisTab() {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-3 gap-4">
        {[
          { label: "TAM", value: "$32B", desc: "Global Digital Fitness Market", color: "violet" },
          { label: "SAM", value: "$8.4B", desc: "US & English-speaking markets", color: "blue" },
          { label: "SOM", value: "$42M", desc: "Realistic 3-year capture", color: "emerald" },
        ].map((m) => (
          <Card key={m.label}>
            <CardContent className="p-5 text-center">
              <div className={`text-xs font-bold text-${m.color}-400 uppercase tracking-widest mb-2`}>{m.label}</div>
              <div className={`text-3xl font-bold text-${m.color}-400 mb-1`}>{m.value}</div>
              <div className="text-xs text-white/30">{m.desc}</div>
            </CardContent>
          </Card>
        ))}
      </div>

      <Section title="Competitor Analysis" executive="Business Analyst">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-xs text-white/30 border-b border-white/[0.06]">
                <th className="text-left pb-3 pr-4">Competitor</th>
                <th className="text-left pb-3 pr-4">Users</th>
                <th className="text-left pb-3 pr-4">Price</th>
                <th className="text-left pb-3 pr-4">AI Feature</th>
                <th className="text-left pb-3">Your Edge</th>
              </tr>
            </thead>
            <tbody className="space-y-2">
              {[
                { name: "Nike Training Club", users: "100M+", price: "Free/$14.99", ai: "Basic", edge: "✓ Better AI" },
                { name: "Peloton", users: "6.7M", price: "$44/mo", ai: "None", edge: "✓ No hardware needed" },
                { name: "MyFitnessPal", users: "200M+", price: "Free/$19.99", ai: "Minimal", edge: "✓ Workout + Nutrition AI" },
                { name: "Apple Fitness+", users: "10M+", price: "$9.99/mo", ai: "Low", edge: "✓ Platform agnostic" },
                { name: "Freeletics", users: "20M+", price: "$14.99/mo", ai: "Medium", edge: "✓ Superior personalization" },
              ].map((row, i) => (
                <tr key={row.name} className={`border-b border-white/[0.03] ${i % 2 === 0 ? "bg-white/[0.01]" : ""}`}>
                  <td className="py-3 pr-4 font-medium text-white/70">{row.name}</td>
                  <td className="py-3 pr-4 text-white/40">{row.users}</td>
                  <td className="py-3 pr-4 text-white/40">{row.price}</td>
                  <td className="py-3 pr-4 text-white/40">{row.ai}</td>
                  <td className="py-3 text-emerald-400 text-xs">{row.edge}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Section>

      <Section title="Customer Persona" executive="Business Analyst">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[
            {
              name: "Primary: Urban Professional",
              age: "28-38",
              income: "$65K-$120K",
              pain: "No time for gym, wants efficient home workouts",
              goals: "Lose weight, build habits, feel confident",
              channels: "Instagram, LinkedIn, Podcasts",
            },
            {
              name: "Secondary: Fitness Enthusiast",
              age: "22-32",
              income: "$45K-$80K",
              pain: "Bored with standard apps, wants more personalization",
              goals: "Reach peak fitness, track performance",
              channels: "TikTok, YouTube, Reddit r/fitness",
            },
          ].map((persona) => (
            <div key={persona.name} className="p-4 rounded-xl bg-white/[0.03] border border-white/[0.06] space-y-2">
              <div className="text-sm font-semibold text-white">{persona.name}</div>
              {[
                ["Age", persona.age],
                ["Income", persona.income],
                ["Pain Point", persona.pain],
                ["Goals", persona.goals],
                ["Channels", persona.channels],
              ].map(([key, val]) => (
                <div key={key} className="flex gap-2 text-xs">
                  <span className="text-white/30 w-20 flex-shrink-0">{key}:</span>
                  <span className="text-white/60">{val}</span>
                </div>
              ))}
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}

function MarketingTab() {
  return (
    <div className="space-y-4">
      <Section title="Go-to-Market Strategy" executive="CMO">
        <p className="text-sm text-white/55 leading-relaxed mb-4">
          A content-first, community-driven approach targeting organic growth through social proof, influencer partnerships, and viral fitness challenges — minimizing CAC while maximizing brand credibility.
        </p>
        <div className="space-y-3">
          {[
            { phase: "Month 1-3", title: "Foundation & Launch", actions: ["Build audience on TikTok/IG Reels (fitness content)", "Launch beta with 50 hand-picked influencers", "Set up referral program (give 1 month free, get 1 month free)", "Run targeted Meta ads: $2,000/mo budget"] },
            { phase: "Month 4-6", title: "Growth Acceleration", actions: ["Scale ads to $8,000/mo with proven creatives", "Launch affiliate program (20% commission)", "Partner with workplace wellness programs", "PR push: TechCrunch, Healthtech press"] },
            { phase: "Month 7-12", title: "Scale & Retain", actions: ["Content machine: 5 posts/day across platforms", "Launch community features (leaderboards, challenges)", "Corporate B2B outreach (100 target companies)", "Expand to YouTube long-form content"] },
          ].map((phase) => (
            <div key={phase.phase} className="p-4 rounded-xl bg-white/[0.02] border border-white/[0.05]">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-xs px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">{phase.phase}</span>
                <span className="text-sm font-semibold text-white">{phase.title}</span>
              </div>
              <ul className="space-y-1">
                {phase.actions.map((action) => (
                  <li key={action} className="text-xs text-white/45 flex items-start gap-1.5">
                    <span className="text-violet-400 mt-0.5">→</span>{action}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Unit Economics" executive="CMO + CFO">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: "Target CAC", value: "$32", color: "text-blue-400" },
            { label: "LTV (24mo)", value: "$420", color: "text-emerald-400" },
            { label: "LTV:CAC Ratio", value: "13:1", color: "text-violet-400" },
            { label: "Payback Period", value: "1.6 mo", color: "text-amber-400" },
          ].map((m) => (
            <div key={m.label} className="text-center p-4 rounded-xl bg-white/[0.03] border border-white/[0.06]">
              <div className={`text-2xl font-bold ${m.color} mb-1`}>{m.value}</div>
              <div className="text-xs text-white/30">{m.label}</div>
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}

function OperationsTab() {
  return (
    <div className="space-y-4">
      <Section title="Launch Plan" executive="COO">
        <div className="space-y-2">
          {[
            { week: "Weeks 1-2", task: "Finalize MVP feature spec and design system", done: true },
            { week: "Weeks 3-8", task: "Build core AI engine + mobile app (iOS first)", done: false },
            { week: "Weeks 9-10", task: "Beta testing with 50 users, collect feedback", done: false },
            { week: "Weeks 11-12", task: "Iterate on feedback, prepare App Store submission", done: false },
            { week: "Week 13", task: "Soft launch + PR push + influencer activation", done: false },
            { week: "Month 4+", task: "Full growth mode — ads, partnerships, corporate deals", done: false },
          ].map((item) => (
            <div key={item.week} className="flex items-start gap-3 p-3 rounded-xl bg-white/[0.02] border border-white/[0.04]">
              <div className={`size-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 ${item.done ? "bg-emerald-500" : "border border-white/[0.15]"}`}>
                {item.done && (
                  <svg className="size-3 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3">
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                )}
              </div>
              <div>
                <div className="text-xs text-violet-400 font-medium mb-0.5">{item.week}</div>
                <div className="text-sm text-white/65">{item.task}</div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Hiring Plan" executive="COO">
        <div className="space-y-2">
          {[
            { role: "Founding Engineer (Full Stack + AI)", timing: "Month 0", budget: "$8,000/mo" },
            { role: "UX/UI Designer (Part-time)", timing: "Month 0", budget: "$3,000/mo" },
            { role: "Content & Growth Manager", timing: "Month 3", budget: "$4,500/mo" },
            { role: "Customer Success Lead", timing: "Month 6", budget: "$4,000/mo" },
            { role: "Senior AI Engineer", timing: "Month 9 (post-revenue)", budget: "$12,000/mo" },
          ].map((hire) => (
            <div key={hire.role} className="flex items-center justify-between p-3 rounded-xl bg-white/[0.03] border border-white/[0.05]">
              <div>
                <div className="text-sm text-white/70">{hire.role}</div>
                <div className="text-xs text-white/30">{hire.timing}</div>
              </div>
              <span className="text-sm font-semibold text-white/60">{hire.budget}</span>
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}

function TechnologyTab() {
  return (
    <div className="space-y-4">
      <Section title="Recommended Technology Stack" executive="CTO">
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
          {[
            { category: "Mobile", tech: "React Native", reason: "Cross-platform, fast iteration" },
            { category: "Backend API", tech: "Node.js + Fastify", reason: "High performance, TypeScript" },
            { category: "Database", tech: "PostgreSQL + Redis", reason: "Reliable + caching layer" },
            { category: "AI / ML", tech: "OpenAI API + Claude", reason: "State-of-art personalization" },
            { category: "Payments", tech: "Stripe", reason: "Industry standard, easy setup" },
            { category: "Auth", tech: "Clerk", reason: "Fast, secure, social logins" },
            { category: "Infrastructure", tech: "AWS / Vercel", reason: "Scalable, affordable" },
            { category: "Analytics", tech: "Mixpanel + Segment", reason: "User behavior tracking" },
            { category: "Push Notifications", tech: "Expo + OneSignal", reason: "Cross-platform delivery" },
          ].map((item) => (
            <div key={item.category} className="p-3 rounded-xl bg-white/[0.03] border border-white/[0.06]">
              <div className="text-xs text-violet-400 font-medium mb-1">{item.category}</div>
              <div className="text-sm font-semibold text-white mb-0.5">{item.tech}</div>
              <div className="text-[10px] text-white/30">{item.reason}</div>
            </div>
          ))}
        </div>
      </Section>

      <Section title="AI Architecture" executive="CTO">
        <p className="text-sm text-white/55 leading-relaxed">
          The core competitive advantage is an adaptive AI system built on a feedback loop: initial assessment → workout generation → performance tracking → model refinement. Integrate Claude API for natural language coaching interactions and GPT-4 for workout plan generation. Train a custom recommendation model on anonymized user data as you scale. Budget $2,000-$5,000/month for API costs at 10,000 active users.
        </p>
      </Section>
    </div>
  );
}

function RiskTab() {
  return (
    <div className="space-y-4">
      <Section title="Risk Register" executive="Legal Advisor + CEO">
        <div className="space-y-3">
          {[
            { risk: "Market Saturation", impact: "High", probability: "High", mitigation: "Ruthless focus on AI quality as differentiator. Don't compete on price — compete on results." },
            { risk: "User Acquisition Cost Spike", impact: "High", probability: "Medium", mitigation: "Diversify channels early. Never rely solely on paid ads. Build organic content engine." },
            { risk: "AI API Cost Overrun", impact: "Medium", probability: "Medium", mitigation: "Implement usage caps. Build caching layer for common responses. Move to self-hosted models at scale." },
            { risk: "Health Data Privacy (HIPAA)", impact: "High", probability: "Low", mitigation: "Legal review before launch. Do not collect clinical health data. Consult healthcare attorney." },
            { risk: "Churn Rate > 8%/month", impact: "High", probability: "Medium", mitigation: "Onboarding sequences critical. Weekly engagement loops. Gamification. Community features." },
            { risk: "Key Person Dependency", impact: "Medium", probability: "Medium", mitigation: "Document everything. Hire second engineer by Month 4. Redundancy in critical systems." },
          ].map((row) => (
            <div key={row.risk} className="p-4 rounded-xl bg-white/[0.02] border border-white/[0.05]">
              <div className="flex items-center gap-2 mb-2">
                <span className="text-sm font-semibold text-white">{row.risk}</span>
                <Badge variant={row.impact === "High" ? "danger" : "warning"} size="sm">{row.impact} Impact</Badge>
                <Badge variant="default" size="sm">{row.probability} Probability</Badge>
              </div>
              <p className="text-xs text-white/45 leading-relaxed">{row.mitigation}</p>
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}

function RoadmapTab() {
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Section title="30-Day Action Plan" executive="COO">
          <div className="space-y-2">
            {[
              "Register business entity (LLC recommended)",
              "Open business bank account",
              "Set up basic landing page + email capture",
              "Hire founding engineer",
              "Begin UI/UX wireframing",
              "Define MVP feature list (ruthlessly minimal)",
              "Join 3 startup communities for early users",
              "Start documenting idea on social media (build in public)",
              "Research App Store submission requirements",
              "Set up legal agreements + terms of service",
            ].map((task, i) => (
              <div key={task} className="flex items-start gap-2.5">
                <span className="size-5 rounded-full bg-violet-500/10 border border-violet-500/20 text-[10px] text-violet-400 flex items-center justify-center flex-shrink-0 mt-0.5 font-bold">
                  {i + 1}
                </span>
                <span className="text-xs text-white/55">{task}</span>
              </div>
            ))}
          </div>
        </Section>

        <Section title="90-Day Milestones" executive="CEO + COO">
          <div className="space-y-3">
            {[
              { milestone: "Working MVP demo", target: "Day 45", color: "violet" },
              { milestone: "50 beta users signed up", target: "Day 60", color: "blue" },
              { milestone: "First paying customer", target: "Day 75", color: "emerald" },
              { milestone: "App Store submission", target: "Day 80", color: "amber" },
              { milestone: "100 users (paid + free)", target: "Day 90", color: "emerald" },
              { milestone: "$2,000 MRR", target: "Day 90", color: "emerald" },
            ].map((m) => (
              <div key={m.milestone} className="flex items-center justify-between p-3 rounded-xl bg-white/[0.03] border border-white/[0.05]">
                <span className="text-sm text-white/65">{m.milestone}</span>
                <span className={`text-xs font-semibold text-${m.color}-400`}>{m.target}</span>
              </div>
            ))}
          </div>
        </Section>
      </div>

      <Section title="Growth Strategy — Year 1 to Year 3" executive="CEO">
        <div className="grid grid-cols-3 gap-4">
          {[
            {
              period: "Year 1",
              focus: "Launch & Validate",
              kpis: ["500 paying users", "$287K ARR", "NPS > 50", "< 5% monthly churn"],
              color: "violet",
            },
            {
              period: "Year 2",
              focus: "Scale & Expand",
              kpis: ["5,000 paying users", "$1.2M ARR", "Launch Android", "Enter UK/Canada"],
              color: "blue",
            },
            {
              period: "Year 3",
              focus: "Market Leadership",
              kpis: ["20,000 paying users", "$2.4M ARR", "Series A ready", "B2B corporate contracts"],
              color: "emerald",
            },
          ].map((yr) => (
            <div key={yr.period} className={`p-4 rounded-xl bg-${yr.color}-500/5 border border-${yr.color}-500/15`}>
              <div className={`text-xs font-bold text-${yr.color}-400 uppercase tracking-widest mb-1`}>{yr.period}</div>
              <div className="text-sm font-semibold text-white mb-3">{yr.focus}</div>
              <ul className="space-y-1.5">
                {yr.kpis.map((kpi) => (
                  <li key={kpi} className={`text-xs text-${yr.color}-300/70 flex items-start gap-1.5`}>
                    <span className="mt-0.5 flex-shrink-0">→</span>{kpi}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}
